include $(JOT_ROOT)/Makefile.local

LIBNAME = proxy_pattern

SOURCES = proxy_surface.C \
          proxy_stroke.C \
          proxy_texture.C \
          hatching_texture.C \
          proxy_pen.C \
          proxy_pen_ui.C          

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
