include $(JOT_ROOT)/Makefile.local

LIBNAME   = glui

SOURCES = glui_add_controls.C \
			glui.C \
			glui_bitmapbox.C \
			glui_slider.C \
			glui_graph.C \
			glui_bitmap_img_data.C \
			glui_bitmaps.C \
			glui_button.C \
			glui_edittext.C \
			glui_checkbox.C \
			glui_node.C \
			glui_radio.C \
			glui_statictext.C \
			glui_activetext.C \
			glui_panel.C \
			glui_separator.C \
			glui_spinner.C \
			glui_control.C \
			glui_column.C \
			glui_translation.C \
			glui_rotation.C \
			glui_mouse_iaction.C \
			glui_listbox.C \
			glui_rollout.C \
			arcball.C \
			algebra3.C \
			quaternion.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std

