language: cpp
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - freeglut3-dev
    - libglew-dev
    - libxi-dev
    - libxmu-dev
compiler:
    - gcc
    - clang
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
