include $(JOT_ROOT)/Makefile.local

LIBNAME = map3d

SOURCES = map0d3d.C \
         map1d3d.C \
         map2d3d.C \
	 bnode.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
