include $(JOT_ROOT)/Makefile.local

LIBNAME = stroke

SOURCES = hatching_stroke.C \
	  b_stroke_pool.C \
          decal_line_stroke.C \
	  base_stroke.C \
          stroke_generator.C \
          sil_stroke_pool.C \
	  edge_stroke.C \
          edge_stroke_pool.C \
          decal_stroke_pool.C \
          outline_stroke.C \
          gesture_stroke_drawer.C

ALLSRC = $(SOURCES) 

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS  := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
