include $(JOT_ROOT)/Makefile.local

LIBNAME = gest

SOURCES = gesture.C \
          gest_int.C \
          gesture_box_drawer.C \
          pen.C \
          pen_manager.C \
          draw_widget.C \
          mode_name.C \
          vieweasel.C \
          easel_manager.C \
	  patch_pen.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =
FINALCFLAGS =

include $(JOT_ROOT)/include/makefiles/std
