include $(JOT_ROOT)/Makefile.local

LIBNAME    = disp

SOURCES = bbox.C \
         cam.C \
         cam_focus.C \
         color.C \
         gel.C \
         gel_filt.C \
	 ray.C \
         view.C \
         recorder.C \
         animator.C \
         gel_set.C \
         paper_effect_base.C
          
ALLSRC  = $(SOURCES) 

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS  := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
