include $(JOT_ROOT)/Makefile.local

LIBNAME = ffs

SOURCES = circle_widget.C \
          crease_widget.C \
          crv_sketch.C \
          cursor3d.C \
          draw_manip.C \
          draw_pen.C \
          extender.C \
          roof.C \
          ffs_util.C \
          floor.C \
          inflate.C \
          oversketch.C \
          profile.C \
          paper_doll.C \
          select_widget.C \
          sweep.C \
          trace.C \
	  xform_pen.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =
FINALCFLAGS =

include $(JOT_ROOT)/include/makefiles/std
