include $(JOT_ROOT)/Makefile.local

LIBNAME    = manip

SOURCES = cam_pz.C \
         cam_fp.C \
         cam_edit.C \
         manip.C \
         mmenu.C \
         key_menu.C
	 
ALLSRC  = $(SOURCES) 

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS  := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
