include $(JOT_ROOT)/Makefile.local

LIBNAME    = glew

SOURCES = glew.C \
          glew_singleton.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std








