include $(JOT_ROOT)/Makefile.local

LIBNAME = wnpr

SOURCES = halo_sphere.C \
          hatching_pen.C \
          hatching_pen_ui.C \
          line_pen.C \
          line_pen_ui.C \
          npr_pen.C \
          npr_pen_ui.C \
          paper_ui.C \
          sil_ui.C \
          sky_box.C \
          stroke_ui.C \
          view_ui.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =
FINALCFLAGS =

include $(JOT_ROOT)/include/makefiles/std
