include $(JOT_ROOT)/Makefile.local

LIBNAME    = widgets

SOURCES =fps.C \
         kbd_nav.C \
         collide.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = $(OGL_INCS)
LIBRARYDFLAGS =

FINALCFLAGS  := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
