/*****************************************************************
 * This file is part of jot-lib (or "jot" for short):
 *   <http://code.google.com/p/jot-lib/>
 * 
 * jot-lib is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 * 
 * jot-lib is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with jot-lib.  If not, see <http://www.gnu.org/licenses/>.`
 *****************************************************************/

/**********************************************************************
 * tex_coord_gen.H:
 **********************************************************************/
#ifndef TEX_COORD_GEN_H_IS_INCLUDED
#define TEX_COORD_GEN_H_IS_INCLUDED

#include "bface.H"

class TexCoordGen {
 protected:

 public:
   virtual ~TexCoordGen() {}

   // can be used to setup automatic
   // texture coordinate generation:
   virtual void setup() = 0;

   // return texture coordinates for a 
   // given vertex of a given face:
   virtual UVpt uv_from_vert(CBvert*, CBface*) {

      // SUBCLASSES: YOUR CODE HERE

      return UVpt::Origin();
   }

protected:
   //base functionality 

   /*
   This function is designed to fix seems created by automatic 
   assignment of texture coordinates. 
   In order to use this pass the newly assigned texture coordinate as "fix_this_coord"
   and pass the two other texture coordinates for this face as "coord2"  and "coord3"
   all coordinates must be generated by the same formula without fixing them.

   The function will consitently change only one coordinate per face, so you can call it
   with the same coordinates in different order and it will only do the fix once.

   If you're still unsure how to use it see "gl_sphir_tex_coord.C"  for reference
   */
   UVpt fix_seems(CUVpt& fix_this_coord, CUVpt& coord2, CUVpt& coord3);

   double fix_range(double main_x, double x2, double x3 );


};

#endif // TEX_COORD_GEN_H_IS_INCLUDED

/* end of file tex_coord_gen.H */
