include $(JOT_ROOT)/Makefile.local

LIBNAME    = glut_winsys

SOURCES = glut_winsys.C \
           kbd.C \
           mouse.C \
           glui_menu.C \
           glui_dialogs.C

ALLSRC  = $(SOURCES) 

LIBRARYCFLAGS = 
LIBRARYIFLAGS = $(OGL_INCS) $(GLUT_INCS)
LIBRARYDFLAGS =

FINALCFLAGS  := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
