include $(JOT_ROOT)/Makefile.local

LIBNAME    = std

SOURCES = hash.C \
         strpool.C \
         config.C \
	 file.C \
	 error.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = 
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std
