include $(JOT_ROOT)/Makefile.local

LIBNAME    = net

SOURCES = mem_push.C \
         stream.C \
         net.C \
         net_types.C \
         data_item.C \
	 jotappconfig.C \
	 io_manager.C

ALLSRC  = $(SOURCES)

LIBRARYCFLAGS =
LIBRARYIFLAGS = 
LIBRARYDFLAGS =

FINALCFLAGS   := $(FINALCFLAGS)

include $(JOT_ROOT)/include/makefiles/std

